name: launcher0
description: A new Flutter project.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  provider: ^6.0.5  
  installed_apps: ^1.3.1
  shared_preferences: ^2.1.0
  # android_intent_plus: ^3.1.9  
  table_calendar: ^3.0.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
